# 03 · Selecting & Filtering Data

This is the pandas equivalent of a SQL `WHERE` clause and `SELECT` column list — arguably the
skill you'll use most, every single day.

In [1]:
import pandas as pd

df = pd.read_csv("../data/synthetic_ap_invoices.csv", parse_dates=["Invoice Date"])
df.head(2)

,Invoice Number,Vendor Code,Region,Invoice Date,Invoice Amount,Currency,PO Number,Hold Reason,Payment Status
0,US20-INV-200207,V771155,US20,2026-05-09,22435.19,EUR,PO1397710,NaN,On Hold
1,UK30-INV-200191,V431236,UK30,2026-03-03,12379.09,EUR,PO9195810,NaN,On Hold

## Selecting columns

In [2]:
df['Invoice Amount']          # a single column -> returns a Series

0      22435.19
1      12379.09
2      17306.31
3       8862.10
4      17025.69
         ...
300     3599.86
301     5404.48
302     3102.63
303     9356.23
304     1580.34
Name: Invoice Amount, Length: 305, dtype: float64

In [3]:
df[['Invoice Number', 'Invoice Amount', 'Hold Reason']]   # multiple columns -> returns a DataFrame

      Invoice Number  Invoice Amount        Hold Reason
0    US20-INV-200207        22435.19                NaN
1    UK30-INV-200191        12379.09                NaN
2    US20-INV-200222        17306.31                NaN
3    US20-INV-200177         8862.10   Price Difference
4    DE10-INV-200260        17025.69  Quantity Mismatch
..               ...             ...                ...
300  FR15-INV-200203         3599.86   Price Difference
301  DE10-INV-200255         5404.48         Missing GR
302  US20-INV-200072         3102.63   Approval Pending
303  DE10-INV-200235         9356.23   Approval Pending
304  US20-INV-200037         1580.34                NaN

[305 rows x 3 columns]

## `.loc` vs `.iloc`

- `.loc` selects by **label** (column name, index label)
- `.iloc` selects by **integer position** (like list indexing)

This distinction trips up almost every beginner, so let's be explicit.

In [4]:
df.loc[0]                     # row with index label 0

Invoice Number        US20-INV-200207
Vendor Code                   V771155
Region                           US20
Invoice Date      2026-05-09 00:00:00
Invoice Amount               22435.19
Currency                          EUR
PO Number                   PO1397710
Hold Reason                       NaN
Payment Status                On Hold
Name: 0, dtype: object

In [5]:
df.loc[0, 'Invoice Amount']   # value at row 0, column 'Invoice Amount'

np.float64(22435.19)

In [6]:
df.iloc[0]                    # first row by position (same result here since index is default 0..n)

Invoice Number        US20-INV-200207
Vendor Code                   V771155
Region                           US20
Invoice Date      2026-05-09 00:00:00
Invoice Amount               22435.19
Currency                          EUR
PO Number                   PO1397710
Hold Reason                       NaN
Payment Status                On Hold
Name: 0, dtype: object

In [7]:
df.iloc[0:5, 0:3]             # first 5 rows, first 3 columns, by position

    Invoice Number Vendor Code Region
0  US20-INV-200207     V771155   US20
1  UK30-INV-200191     V431236   UK30
2  US20-INV-200222     V744167   US20
3  US20-INV-200177     V154886   US20
4  DE10-INV-200260     V431236   DE10

## Boolean filtering — the real workhorse

You write a condition, pandas returns True/False for every row, then you use that to filter.

In [8]:
on_hold = df[df['Hold Reason'].notna()]
on_hold.shape

(196, 9)

In [9]:
high_value = df[df['Invoice Amount'] > 10000]
high_value[['Invoice Number', 'Invoice Amount']].head()

    Invoice Number  Invoice Amount
0  US20-INV-200207        22435.19
1  UK30-INV-200191        12379.09
2  US20-INV-200222        17306.31
4  DE10-INV-200260        17025.69
6  UK30-INV-200271        16201.04

In [10]:
# Combine conditions: & = AND, | = OR — always wrap each condition in parentheses
de_high_value_holds = df[
    (df['Region'] == 'DE10') &
    (df['Invoice Amount'] > 5000) &
    (df['Hold Reason'].notna())
]
de_high_value_holds.shape

(32, 9)

In [11]:
# .isin() for matching against a list of values — cleaner than chained OR conditions
priority_reasons = df[df['Hold Reason'].isin(['Price Difference', 'Duplicate Invoice'])]
priority_reasons['Hold Reason'].value_counts()

Hold Reason
Price Difference     36
Duplicate Invoice    30
Name: count, dtype: int64

## `.query()` — a readable alternative for complex filters

Handy when conditions get long; reads closer to plain English / SQL.

In [12]:
df.query("Region == 'UK30' and `Invoice Amount` > 8000").head()

,Invoice Number,Vendor Code,Region,Invoice Date,Invoice Amount,Currency,PO Number,Hold Reason,Payment Status
1,UK30-INV-200191,V431236,UK30,2026-03-03,12379.09,EUR,PO9195810,NaN,On Hold
6,UK30-INV-200271,V299041,UK30,2026-03-15,16201.04,GBP,PO7849486,NaN,On Hold
10,UK30-INV-200051,V628178,UK30,2026-02-20,17700.12,EUR,PO5261946,Missing GR,On Hold
15,UK30-INV-200271,V299041,UK30,2026-03-15,16201.04,GBP,PO7849486,NaN,On Hold
20,UK30-INV-200011,V370936,UK30,2026-07-19,18809.15,GBP,PO2922135,NaN,On Hold

## Exercise

1. Filter to invoices from `US20` region with `Payment Status == 'Pending'`.
2. Find all invoices with `Invoice Amount` missing (`.isna()`).
3. Using `.loc`, select just the `Invoice Number` and `Vendor Code` columns for rows where `Hold Reason` is `'Missing PO'`.

In [13]:
# Your code here